language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: "Verify contract on Provider"
      script: |
        pwd

        mkdir -p providers/springboot-provider/build/pacts

        echo ">>> run unit tests and pact tests for consumer app and generate a pact file:"
        ./gradlew :consumer:check

        echo ">>> publish the pact file from the consumer to provider projects:"
        ./gradlew publishWorkshopPact

        echo ">>> verify the Dropwizard provider using a JUnit test:"
        ./gradlew :providers:dropwizard-provider:test
