language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - |
    ls -la
    pwd
    ./gradlew :consumer:check
    ./gradlew publishWorkshopPact
    ./gradlew :providers:dropwizard-provider:test
