language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: "Consumer"
      name: "Run tests & publish contract"
      script: |
        echo ">>> run tests for consumer app and generate pact file(s):"
        ./gradlew :consumer:check

        echo ">>> Publish pact file(s) to Pact Broker:"
        ./gradlew consumer:pactPublish

    - stage: "Verify contract on Provider"
      name: "Dropwizard Provider"
      script: |
        echo ">>> verify the Dropwizard provider using a JUnit test:"
        ./gradlew :providers:dropwizard-provider:test --info

    - name: "Springboot Provider"
      script: |
        echo ">>> verify the springboot provider and publish results back to Pact Broker"
        ./gradlew :providers:springboot-provider:pactVerify
